"""
ACGS-2 Enterprise SSO Integration
Constitutional Hash: 608508a9bd224290

Integrates Enterprise SSO with Multi-Tenancy and MACI frameworks.
Provides unified authentication layer for the Enhanced Agent Bus.

Phase 10 Task 2: Enterprise SSO & Identity Management Integration

Features:
- Multi-tenant SSO configuration
- SAML 2.0 and OIDC provider integration
- MACI role mapping from IdP groups
- Tenant-aware session management
- Identity federation across tenants
"""

try:
    from enhanced_agent_bus._compat.constants import CONSTITUTIONAL_HASH
except ImportError:
    CONSTITUTIONAL_HASH = "standalone"

from .gap_analysis import (
    ConstitutionalGap,
    ConstitutionalPolicyScanner,
    GapCategory,
    GapClassifier,
    GapSeverity,
    GapStatus,
    GapTracker,
    GapTrackingDashboard,
    PolicyLocation,
    RemediationEngine,
    RemediationSuggestion,
    RemediationType,
    ScanResult,
)
from .integration import (
    EnterpriseSSOService,
    SSOAuthenticationResult,
    SSOIntegrationError,
    SSOSession,
    SSOUser,
)
from .integration_config import (
    EncryptionService,
    IntegrationAuditService,
    IntegrationConfig,
    IntegrationConfigService,
    IntegrationHealthChecker,
    IntegrationStatus,
    IntegrationType,
)
from .kafka_streaming import (
    AcknowledgmentMode,
    ConsumerConfig,
    DeadLetterQueue,
    DeliveryGuarantee,
    EventSchema,
    GovernanceEvent,
    GovernanceEventConsumer,
    GovernanceEventProducer,
    KafkaConfig,
    KafkaConnectionError,
    KafkaConnectionPool,
    KafkaEventPublisher,
    ProducerConfig,
    PublishResult,
    SchemaFormat,
    SchemaRegistry,
    SchemaRegistryError,
    SerializationError,
)
from .middleware import (
    SSOAuthenticationMiddleware,
    SSOMiddlewareConfig,
    SSOSessionContext,
    clear_sso_session,
    get_current_sso_session,
    require_sso_authentication,
    set_sso_session,
)
from .migration_job_api import (
    AsyncTaskQueue,
    MigrationJob,
    MigrationJobAPI,
    MigrationJobConfig,
    MigrationJobManager,
    MigrationJobProgress,
    MigrationJobResult,
    MigrationJobStatus,
    MigrationJobType,
    PDFReport,
    PDFReportGenerator,
    ProgressCalculator,
    ReportFormat,
)
from .migration_tools import (
    AgreementStatus,
    DecisionLogImporter,
    DecisionSource,
    ImportedDecision,
    ImportResult,
    ImportStatus,
    SchemaMapping,
    ShadowDecisionResult,
    ShadowModeExecutor,
    ShadowModeMetrics,
    ShadowModeState,
    TrafficConfig,
    TrafficRouter,
)
from .policy_converter import (
    ConversionReport,
    ConversionResult,
    ConversionSeverity,
    ConversionWarning,
    OPAValidator,
    PolicyConverter,
    PolicyFormat,
)
from .protocols import (
    AuthorizationRequest,
    BaseProtocolHandler,
    OIDCHandler,
    ProtocolHandlerFactory,
    ProtocolValidationResult,
    SAML2Handler,
)
from .role_mapping import (
    RoleMapping,
    RoleMappingCache,
    RoleMappingResult,
    RoleMappingService,
    RoleMappingSource,
)
from .saga_migration_integration import (
    CheckpointStore,
    MigrationCheckpoint,
    MigrationPhase,
    SagaMigrationConfig,
    SagaMigrationResult,
    SagaMigrationService,
)
from .saga_orchestration import (
    CompensationStrategy,
    MigrationSagaBuilder,
    Saga,
    SagaContext,
    SagaDefinition,
    SagaEvent,
    SagaEventPublisher,
    SagaEventType,
    SagaExecutionResult,
    SagaMetrics,
    SagaOrchestrator,
    SagaRecoveryService,
    SagaStatus,
    SagaStepDefinition,
    SagaStepExecution,
    SagaStepResult,
    SagaStepStatus,
    SagaStore,
)
from .session_governance_sdk import (
    ConcurrencyPolicy,
    Session,
    SessionAnalytics,
    SessionConfig,
    SessionEvent,
    SessionEventType,
    SessionGovernanceClient,
    SessionGovernancePolicy,
    SessionLifecycleManager,
    SessionMonitor,
    SessionState,
    SessionToken,
    SessionTokenManager,
    SessionValidationResult,
    TenantSessionStore,
)
from .tenant_sso_config import (
    AttributeMapping,
    IdPProviderType,
    OIDCConfig,
    RoleMappingRule,
    SAMLConfig,
    SSOProtocolType,
    TenantIdPConfig,
    TenantSSOConfig,
    TenantSSOConfigManager,
)

__all__ = [
    # Constants
    "CONSTITUTIONAL_HASH",
    "AcknowledgmentMode",
    "AgreementStatus",
    "AsyncTaskQueue",
    "AttributeMapping",
    "AuthorizationRequest",
    # Protocol Handlers
    "BaseProtocolHandler",
    # Saga-Migration Integration
    "CheckpointStore",
    # Saga Orchestration
    "CompensationStrategy",
    "ConcurrencyPolicy",
    "ConstitutionalGap",
    "ConstitutionalPolicyScanner",
    "ConsumerConfig",
    "ConversionReport",
    "ConversionResult",
    "ConversionSeverity",
    "ConversionWarning",
    "DeadLetterQueue",
    "DecisionLogImporter",
    "DecisionSource",
    # Kafka Event Streaming Integration
    "DeliveryGuarantee",
    "EncryptionService",
    # Integration Service
    "EnterpriseSSOService",
    "EventSchema",
    "GapCategory",
    "GapClassifier",
    # Constitutional Gap Analysis
    "GapSeverity",
    "GapStatus",
    "GapTracker",
    "GapTrackingDashboard",
    "GovernanceEvent",
    "GovernanceEventConsumer",
    "GovernanceEventProducer",
    "IdPProviderType",
    "ImportResult",
    # Migration Tools
    "ImportStatus",
    "ImportedDecision",
    "IntegrationAuditService",
    "IntegrationConfig",
    "IntegrationConfigService",
    "IntegrationHealthChecker",
    "IntegrationStatus",
    # Enterprise Integration Configuration
    "IntegrationType",
    "KafkaConfig",
    "KafkaConnectionError",
    "KafkaConnectionPool",
    "KafkaEventPublisher",
    "MigrationCheckpoint",
    "MigrationJob",
    "MigrationJobAPI",
    "MigrationJobConfig",
    "MigrationJobManager",
    "MigrationJobProgress",
    "MigrationJobResult",
    # Migration Job Management API
    "MigrationJobStatus",
    "MigrationJobType",
    "MigrationPhase",
    "MigrationSagaBuilder",
    "OIDCConfig",
    "OIDCHandler",
    "OPAValidator",
    "PDFReport",
    "PDFReportGenerator",
    "PolicyConverter",
    # Legacy Policy Conversion
    "PolicyFormat",
    "PolicyLocation",
    "ProducerConfig",
    "ProgressCalculator",
    "ProtocolHandlerFactory",
    "ProtocolValidationResult",
    "PublishResult",
    "RemediationEngine",
    "RemediationSuggestion",
    "RemediationType",
    "ReportFormat",
    "RoleMapping",
    "RoleMappingCache",
    "RoleMappingResult",
    "RoleMappingRule",
    # MACI Role Mapping
    "RoleMappingService",
    "RoleMappingSource",
    "SAML2Handler",
    "SAMLConfig",
    # Middleware
    "SSOAuthenticationMiddleware",
    "SSOAuthenticationResult",
    "SSOIntegrationError",
    "SSOMiddlewareConfig",
    "SSOProtocolType",
    "SSOSession",
    "SSOSessionContext",
    "SSOUser",
    "Saga",
    "SagaContext",
    "SagaDefinition",
    "SagaEvent",
    "SagaEventPublisher",
    "SagaEventType",
    "SagaExecutionResult",
    "SagaMetrics",
    "SagaMigrationConfig",
    "SagaMigrationResult",
    "SagaMigrationService",
    "SagaOrchestrator",
    "SagaRecoveryService",
    "SagaStatus",
    "SagaStepDefinition",
    "SagaStepExecution",
    "SagaStepResult",
    "SagaStepStatus",
    "SagaStore",
    "ScanResult",
    "SchemaFormat",
    "SchemaMapping",
    "SchemaRegistry",
    "SchemaRegistryError",
    "SerializationError",
    "Session",
    "SessionAnalytics",
    "SessionConfig",
    "SessionEvent",
    "SessionEventType",
    "SessionGovernanceClient",
    "SessionGovernancePolicy",
    "SessionLifecycleManager",
    "SessionMonitor",
    # Session Governance SDK
    "SessionState",
    "SessionToken",
    "SessionTokenManager",
    "SessionValidationResult",
    "ShadowDecisionResult",
    "ShadowModeExecutor",
    "ShadowModeMetrics",
    "ShadowModeState",
    "TenantIdPConfig",
    # Tenant SSO Configuration
    "TenantSSOConfig",
    "TenantSSOConfigManager",
    "TenantSessionStore",
    "TrafficConfig",
    "TrafficRouter",
    "clear_sso_session",
    "get_current_sso_session",
    "require_sso_authentication",
    "set_sso_session",
]
