"""ACGS: Constitutional AI Governance for Any Agent.

Copyright (C) 2024-2026 ACGS Contributors
Licensed under Apache-2.0. See LICENSE for details.
Commercial license available at https://acgs.ai for proprietary use.

This module is the canonical ``acgs`` import namespace. It re-exports the full
``acgs_lite`` public API so users can write::

    from acgs import Constitution, GovernedAgent, MACIRole

    constitution = Constitution.from_yaml("rules.yaml")
    agent = GovernedAgent(my_agent, constitution=constitution)
    result = agent.run("process this request")

``acgs_lite`` remains available as a compatibility import namespace.

Constitutional Hash: 608508a9bd224290
"""

from acgs_lite import (
    AcknowledgedTension,
    ActionContext,
    ActionEnvelope,
    ActionPayloadSummary,
    ActionRequirements,
    ActionType,
    ActivationRecord,
    ActorRef,
    ActorRole,
    ApprovalReviewRequest,
    ApprovalReviewResponse,
    ApprovalSubmission,
    AuditBackend,
    AuditEntry,
    AuditEvent,
    AuditEventType,
    AuditLog,
    BatchValidationResult,
    BundleStatus,
    BundleStore,
    ComplianceResult,
    ComplianceStatus,
    ConcurrentLifecycleError,
    Constitution,
    ConstitutionalViolationError,
    ConstitutionBuilder,
    ConstitutionBundle,
    ConstitutionLifecycle,
    DecisionType,
    ExecutionOutcome,
    ExternalRef,
    GovernanceCircuitBreaker,
    GovernanceDecision,
    GovernanceEngine,
    GovernanceError,
    GovernanceHaltError,
    GovernanceStateBackend,
    GovernanceStateChecksumError,
    GovernanceStateError,
    GovernanceStateMigrationError,
    GovernanceStateObservabilityHook,
    GovernanceStateVersionError,
    GovernedAgent,
    GovernedCallable,
    InMemoryAuditBackend,
    InMemoryBundleStore,
    InMemoryGovernanceStateBackend,
    InMemoryLifecycleAuditSink,
    JsonFileGovernanceStateBackend,
    JSONLAuditBackend,
    LicenseInfo,
    LicenseManager,
    LifecycleAuditSink,
    LifecycleError,
    LifecycleEvidenceError,
    LifecycleEvidenceRecord,
    MACIEnforcer,
    MACIRole,
    MACIViolationError,
    OperationType,
    OutcomeStatus,
    RedisGovernanceStateBackend,
    ResourceRef,
    RiskLevel,
    Rule,
    RuleSnapshot,
    RuleSynthesisProvider,
    Severity,
    SQLiteGovernanceStateBackend,
    StatusTransition,
    Tier,
    ValidationResult,
    ViolationAction,
    __constitutional_hash__,
    __version__,
    create_openshell_governance_app,
    create_openshell_governance_router,
    set_license,
)

__all__ = [
    # Core
    "Constitution",
    "ConstitutionBuilder",
    "ConstitutionBundle",
    "Rule",
    "RuleSynthesisProvider",
    "AcknowledgedTension",
    "ActivationRecord",
    "BundleStatus",
    "BundleStore",
    "InMemoryBundleStore",
    "RuleSnapshot",
    "Severity",
    "StatusTransition",
    "ViolationAction",
    # Lifecycle (Week 2)
    "ConstitutionLifecycle",
    "LifecycleError",
    "LifecycleEvidenceError",
    "ConcurrentLifecycleError",
    "LifecycleEvidenceRecord",
    "LifecycleAuditSink",
    "InMemoryLifecycleAuditSink",
    # Engine
    "GovernanceEngine",
    "ValidationResult",
    "BatchValidationResult",
    # Wrappers
    "GovernedAgent",
    "GovernedCallable",
    # Audit
    "AuditLog",
    "AuditEntry",
    "AuditBackend",
    "AuditEvent",
    "AuditEventType",
    "InMemoryAuditBackend",
    "JSONLAuditBackend",
    # Circuit breaker (Article 14 kill-switch)
    "GovernanceCircuitBreaker",
    "GovernanceHaltError",
    # MACI
    "MACIRole",
    "MACIEnforcer",
    # OpenShell governance integration
    "ActionContext",
    "ActionEnvelope",
    "ActionPayloadSummary",
    "ActionRequirements",
    "ActionType",
    "ActorRef",
    "ActorRole",
    "ApprovalReviewRequest",
    "ApprovalReviewResponse",
    "ApprovalSubmission",
    "ComplianceResult",
    "ComplianceStatus",
    "DecisionType",
    "ExecutionOutcome",
    "ExternalRef",
    "GovernanceStateChecksumError",
    "GovernanceDecision",
    "GovernanceStateBackend",
    "GovernanceStateError",
    "GovernanceStateMigrationError",
    "GovernanceStateObservabilityHook",
    "GovernanceStateVersionError",
    "InMemoryGovernanceStateBackend",
    "JsonFileGovernanceStateBackend",
    "OperationType",
    "OutcomeStatus",
    "RedisGovernanceStateBackend",
    "ResourceRef",
    "RiskLevel",
    "SQLiteGovernanceStateBackend",
    "create_openshell_governance_app",
    "create_openshell_governance_router",
    # Errors
    "ConstitutionalViolationError",
    "GovernanceError",
    "MACIViolationError",
    # Licensing
    "set_license",
    "LicenseInfo",
    "LicenseManager",
    "Tier",
    # Metadata
    "__constitutional_hash__",
    "__version__",
]
