"""Bittensor protocol configuration and shared types.

Defines escalation categories, miner/validator configuration,
and the constitutional hash verification contract.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class EscalationType(Enum):
    """Categories of governance escalation.

    These are a working taxonomy — empirical percentages will be
    generated by the live subnet. See 07-subnet-concept-qa-responses.md
    Section 2 for rationale.
    """

    CONSTITUTIONAL_CONFLICT = "constitutional_conflict"
    CONTEXT_SENSITIVITY = "context_sensitivity"
    STAKEHOLDER_IRRECONCILABILITY = "stakeholder_irreconcilability"
    EDGE_CASE_AMBIGUITY = "edge_case_ambiguity"
    UNKNOWN = "unknown"


class MinerTier(Enum):
    """Qualification tiers for complexity-based task routing."""

    APPRENTICE = "apprentice"    # < 10 validated judgments
    JOURNEYMAN = "journeyman"   # >= 10, reputation >= 1.2
    MASTER = "master"           # >= 50, reputation >= 1.5, domain specialist
    ELDER = "elder"             # >= 200, precedent-setting


TIER_TAO_MULTIPLIER: dict[MinerTier, float] = {
    MinerTier.APPRENTICE: 1.0,
    MinerTier.JOURNEYMAN: 1.5,
    MinerTier.MASTER: 2.5,
    MinerTier.ELDER: 4.0,
}

TIER_REQUIREMENTS: dict[MinerTier, dict[str, Any]] = {
    MinerTier.APPRENTICE: {"min_validated": 0, "min_reputation": 0.0},
    MinerTier.JOURNEYMAN: {"min_validated": 10, "min_reputation": 1.2},
    MinerTier.MASTER: {"min_validated": 50, "min_reputation": 1.5},
    MinerTier.ELDER: {"min_validated": 200, "min_reputation": 1.8},
}


@dataclass(frozen=True, slots=True)
class MinerConfig:
    """Configuration for a constitutional swarm miner.

    Miners carry embedded AgentDNA with EXECUTOR role.
    Constitution hash must match the SN Owner's active constitution.
    """

    constitution_path: str
    agent_id: str = "miner"
    capabilities: tuple[str, ...] = ()
    domains: tuple[str, ...] = ()
    tier: MinerTier = MinerTier.APPRENTICE
    strict_dna: bool = True
    validate_output: bool = True


@dataclass(frozen=True, slots=True)
class ValidatorConfig:
    """Configuration for a constitutional swarm validator.

    Validators run ConstitutionalMesh with JUDICIAL role.
    GovernanceManifold enabled by default for trust projection.
    """

    constitution_path: str
    peers_per_validation: int = 3
    quorum: int = 2
    use_manifold: bool = True
    authenticity_detection: bool = False
    reputation_decay_rate: float = 0.01


@dataclass
class SubnetMetrics:
    """Operational metrics tracked by the SN Owner."""

    total_escalations: int = 0
    total_judgments: int = 0
    total_validations: int = 0
    escalation_type_counts: dict[str, int] = field(default_factory=dict)
    avg_judgment_time_seconds: float = 0.0
    avg_authenticity_score: float = 0.0
    precedents_created: int = 0
    active_miners: int = 0
    active_validators: int = 0
    constitution_hash: str = ""
    manifold_spectral_bound: float = 0.0
    manifold_is_stable: bool = True

    def record_escalation(self, escalation_type: EscalationType) -> None:
        """Record an escalation event."""
        self.total_escalations += 1
        key = escalation_type.value
        self.escalation_type_counts[key] = self.escalation_type_counts.get(key, 0) + 1

    def escalation_distribution(self) -> dict[str, float]:
        """Get the empirical distribution of escalation types.

        This is the data that the subnet generates over time —
        the answer to Question 2 (failure mode percentages).
        """
        if self.total_escalations == 0:
            return {}
        return {
            etype: count / self.total_escalations
            for etype, count in self.escalation_type_counts.items()
        }
